Enabled:
  NoContainers:
    approved_images: ["ubuntu-latest"]
  SpecialPermissions:
  EmptyName:
  RiskyTriggers:
  UnapprovedRunners:
    allowed_runners: ["ubuntu-latest", "macos-12", "macos-15", "macos-latest", "mobile_linux_8_core", "self-hosted"]
  CommandInjection:
  AutomaticMerge:
  UnpinnedAction:
    trusted_authors: ["Betterment", "actions", "anthropics"]
  UnsafeCheckout:
  InheritedSecrets:
  BulkPermissions:
  Shellcheck:
    shellcheck_bin: "/usr/bin/shellcheck"
  CheckoutWithStaticCredentials:
